name: abacatepay
description: A Dart/Flutter SDK for AbacatePay payment API.
version: 1.0.0
repository: https://github.com/feliperfdev/abacatepay-dart-sdk

environment:
  sdk: ^3.7.2

dependencies:
  http: ^1.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
