name: abacatepay
description: AbacatePay Dart/Flutter SDK for you to start receiving payments in seconds
version: 1.0.2+2
repository: https://github.com/feliperfdev/abacatepay-dart-sdk

environment:
  sdk: ^3.7.2

dependencies:
  http: ^1.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
